[package]
name = "light-speed-io"
version = "0.0.1"
edition = "2021"
license = "MIT"
homepage = "https://github.com/JackKelly/light-speed-io"
repository = "https://github.com/JackKelly/light-speed-io"
readme = "README.md"

[lib]
crate-type = ["lib"]   # The crate types to generate.

[dependencies]
anyhow = "1.0"
bytes = "1.5.0"
crossbeam = "0.8.4"
delegate = "0.12.0"
io-uring = "0.6"
libc = "0.2"  # Just used for libc::O_DIRECT in src/io_uring.rs
nix = "0.27"
object_store = "0.9.0"
tokio = "1.35.1"
url = "2.5.0"
