[package]
name = "light-speed-io"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io-uring = "0.6"
libc = "0.2"  # Just used for libc::O_DIRECT in src/io_uring.rs
